export const ROLES = {
    ManageAuthor: 'ROLE_MANAGE_AUTHOR',
    ManageNewsArticle: 'ROLE_MANAGE_NEWS_ARTICLE',
    ManageUser: 'ROLE_MANAGE_USER',
    ManageClassificationSymbol: 'ROLE_MANAGE_CLASSIFICATION_SYMBOL',
    ManageCategory: 'ROLE_MANAGE_CATEGORY',
    ManageBookSet: 'ROLE_MANAGE_BOOK_SET',
    ManageLog: 'ROLE_MANAGE_LOG',
    ManageRole: 'ROLE_MANAGE_ROLE',
    ManageBook: 'ROLE_MANAGE_BOOK',
    ManageImportReceipt: 'ROLE_MANAGE_IMPORT_RECEIPT',
    ManageBookDefinition: 'ROLE_MANAGE_BOOK_DEFINITION',
    ManageCategoryGroup: 'ROLE_MANAGE_CATEGORY_GROUP',
    ManagePublisher: 'ROLE_MANAGE_PUBLISHER',
    ManageSystemSettings: 'ROLE_MANAGE_SYSTEM_SETTINGS',
    ManageBorrowReceipt: 'ROLE_MANAGE_BORROW_RECEIPT',
    ManageReader: 'ROLE_MANAGE_READER',
    Reader: 'ROLE_READER',
};

export const ROLE_LABELS = {
    ROLE_READER: 'Độc giả',
    ROLE_MANAGE_AUTHOR: 'Quản lý tác giả',
    ROLE_MANAGE_NEWS_ARTICLE: 'Quản lý bài viết',
    ROLE_MANAGE_USER: 'Quản lý người dùng',
    ROLE_MANAGE_CLASSIFICATION_SYMBOL: 'Quản lý ký hiệu phân loại',
    ROLE_MANAGE_CATEGORY: 'Quản lý danh mục',
    ROLE_MANAGE_BOOK_SET: 'Quản lý bộ sách',
    ROLE_MANAGE_LOG: 'Quản lý nhật ký',
    ROLE_MANAGE_ROLE: 'Quản lý vai trò',
    ROLE_MANAGE_BOOK: 'Quản lý sách',
    ROLE_MANAGE_IMPORT_RECEIPT: 'Quản lý biên nhận nhập khẩu',
    ROLE_MANAGE_BOOK_DEFINITION: 'Quản lý định nghĩa sách',
    ROLE_MANAGE_CATEGORY_GROUP: 'Quản lý nhóm danh mục',
    ROLE_MANAGE_PUBLISHER: 'Quản lý nhà xuất bản',
    ROLE_MANAGE_BORROW_RECEIPT: 'Quản lý phiếu mượn',
    ROLE_MANAGE_READER: 'Quản lý bạn đọc',
};

export const ROLE_NAMES = {
    ROLE_READER: 'Độc giả',
    ROLE_MANAGE_AUTHOR: 'Quản lý tác giả',
    ROLE_MANAGE_NEWS_ARTICLE: 'Quản lý bài viết',
    ROLE_MANAGE_USER: 'Quản lý người dùng',
    ROLE_MANAGE_CLASSIFICATION_SYMBOL: 'Quản lý ký hiệu phân loại',
    ROLE_MANAGE_CATEGORY: 'Quản lý danh mục',
    ROLE_MANAGE_BOOK_SET: 'Quản lý bộ sách',
    ROLE_MANAGE_LOG: 'Quản lý nhật ký',
    ROLE_MANAGE_ROLE: 'Quản lý vai trò',
    ROLE_MANAGE_BOOK: 'Quản lý sách',
    ROLE_MANAGE_IMPORT_RECEIPT: 'Quản lý biên nhận nhập khẩu',
    ROLE_MANAGE_BOOK_DEFINITION: 'Quản lý định nghĩa sách',
    ROLE_MANAGE_CATEGORY_GROUP: 'Quản lý nhóm danh mục',
    ROLE_MANAGE_PUBLISHER: 'Quản lý nhà xuất bản',
    ROLE_MANAGE_BORROW_RECEIPT: 'Quản lý phiếu mượn',
    ROLE_MANAGE_READER: 'Quản lý bạn đọc',
};

export const ROLE_COLORS = {};
